%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------

# Camera type (0: MONOCULAR, 1: STEREO, 2: RGBD)
Camera.type: 0

# Camera ROS topic
Camera.image0Topic: "/device_0/sensor_1/Color_0/image/data" #"/d400/color/image_raw"

# Camera calibration and distortion parameters (OpenCV) 
Camera.fx: 901.9766845703125
Camera.fy: 900.259521484375
Camera.cx: 635.3535766601562
Camera.cy: 349.8155822753906

Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0

Camera.width: 1280
Camera.height: 720

# Camera frames per second 
Camera.fps: 30.0

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1500

# ORB Extractor: Scale factor between levels in the scale pyramid
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

ORBrefiner.Used: 0
ORBrefiner.Path: "/home/antusheng/Desktop/orb-binary.pt"

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500

#--------------------------------------------------------------------------------------------
# ORB Vocabulary Parameters
#--------------------------------------------------------------------------------------------
Vocabulary.Path: "/home/antusheng/research/map_based_localization/test/ORB_SLAM2_MapReuse/Vocabulary/ORBvoc.txt"

#--------------------------------------------------------------------------------------------
# Map save and reuse Parameters
#--------------------------------------------------------------------------------------------
Map.Path: "/home/antusheng/research/map_based_localization/test/ORB_SLAM2_MapReuse/test_result/map/map.bin"

#--------------------------------------------------------------------------------------------
# Trajectory Parameters
#--------------------------------------------------------------------------------------------
Trajectory.SavePath: "/home/antusheng/research/map_based_localization/test/ORB_SLAM2_MapReuse/test_result/trajectory/"
